fname = input('enter fname:')
lname = input('enter lname:')
age = input('enter age:')
address = input('enter address:')
occupation = input('enter occupation:')
state = input('enter state of origin:')
religion = input('enter religion:')
print('your fname is ' + fname)
print('your lname is ' + lname)
print('your age is ' + age)
print('your address is ' + address)
print('your occupation is ' + occupation)
print('your state of origin is ' + state)
print('your religion is ' + religion)